// GENERATED by tools/gen_params.py from modules/alloyflux/params.json — DO NOT EDIT BY HAND.
#pragma once

#include "ParamDescriptor.h"
#include "params.h"
#include "dsp/ReverbEngine.h"
#include "dsp/DelayEngine.h"
#include "dsp/FxChain.h"

// clang-format off
static const ParamDescriptor kParamManifest[] = {
    {   1, "motion"        , "Motion"                  , "Animation"   ,                   0.0f,                       1.0f,       0.0f, ParamScale::Linear, nullptr, &gMotion, 1.0f },
    {   5, "glidetime"     , "Glide Time"              , "Animation"   ,                   0.0f,                       2.0f,       0.0f, ParamScale::Linear, "s"   , &gGlideTime, 1.0f },
    {   7, "vol"           , "Volume"                  , "Output"      ,                   0.0f,                       1.0f,       1.0f, ParamScale::Linear, nullptr, &gVolume, 1.0f },
    {   8, "space"         , "Space (Stereo Width)"    , "Output"      ,                   0.0f,                       2.0f,       1.0f, ParamScale::Linear, nullptr, &gSpace, 1.0f },
    {  16, "root"          , "Root"                    , "Oscillator"  ,                  27.5f,                    7040.0f,     440.0f, ParamScale::Log , "Hz"  , &gBaseFreq, 1.0f },
    {  71, "curve"         , "Curve"                   , "Envelope"    ,                   0.0f,                       1.0f,       0.5f, ParamScale::Linear, nullptr, &gCurve, 1.0f },
    {  72, "adsrrelease"   , "Release"                 , "Envelope"    ,                 0.001f,                       8.0f,       0.3f, ParamScale::Linear, "s"   , &gAdsrRelease, 1.0f },
    {  73, "adsrattack"    , "Attack"                  , "Envelope"    ,                 0.001f,                       4.0f,      0.05f, ParamScale::Linear, "s"   , &gAdsrAttack, 1.0f },
    {  74, "filtercutoff"  , "Cutoff"                  , "Filter"      ,                  20.0f,                   16000.0f,     983.2f, ParamScale::Log , "Hz"  , &gFilterCutoff, 1.0f },
    {  75, "filterres"     , "Resonance"               , "Filter"      ,                   0.0f,                       1.0f,       0.0f, ParamScale::Linear, nullptr, &gFilterRes, 1.0f },
    {  78, "shape"         , "Shape"                   , "Oscillator"  ,                   0.0f,                       1.0f,       0.0f, ParamScale::Linear, nullptr, &gShape, 1.0f },
    {  82, "adsrdecay"     , "Decay"                   , "Envelope"    ,                 0.001f,                       4.0f,       0.1f, ParamScale::Linear, "s"   , &gAdsrDecay, 1.0f },
    {  83, "adsrsustain"   , "Sustain"                 , "Envelope"    ,                   0.0f,                       1.0f,       0.8f, ParamScale::Linear, nullptr, &gAdsrSustain, 1.0f },
    {  84, "fat"           , "Fatness"                 , "Oscillator"  ,                   0.0f,                       1.0f,       0.4f, ParamScale::Linear, nullptr, &gFatness, 1.0f },
    {  85, "gatelen"       , "Gate Length"             , "Envelope"    ,                   0.0f,                    2000.0f,       0.0f, ParamScale::Linear, "ms"  , &gGateLength, 1.0f },
    {  86, "delaytime"     , "Time"                    , "Delay"       ,                  10.0f,        (float)DELAY_MAX_MS,     100.0f, ParamScale::Linear, "ms"  , &gDelayTime, 1.0f },
    {  87, "delayfb"       , "Feedback"                , "Delay"       ,                   0.0f,                      0.95f,       0.5f, ParamScale::Linear, nullptr, &gDelayFeedback, 1.0f },
    {  88, "curvetime"     , "Time Scale"              , "Envelope"    ,                  0.25f,                       4.0f,       1.0f, ParamScale::Linear, "×"   , &gCurveTime, 1.0f },
    {  89, "dspeed"        , "Drift Speed"             , "Animation"   ,                 0.001f,                       0.1f,      0.04f, ParamScale::Linear, nullptr, &gDriftSpeed, 1.0f },
    {  91, "revmix"        , "Mix"                     , "Reverb"      ,                   0.0f,                       1.0f,       0.0f, ParamScale::Linear, nullptr, const_cast<float *>(&gRevMix), 1.0f },
    {  92, "color"         , "Color"                   , "Oscillator"  ,                   0.0f,                       1.0f,       0.0f, ParamScale::Linear, nullptr, &gColor, 1.0f },
    {  94, "rel"           , "Relation"                , "Oscillator"  ,                   0.0f,                      24.0f,       0.0f, ParamScale::Linear, "st"  , &gRelation, 1.0f },
    {  95, "delaymix"      , "Mix"                     , "Delay"       ,                   0.0f,                       1.0f,       0.0f, ParamScale::Linear, nullptr, &gDelayMix, 1.0f },
    { 112, "revmodspeed"   , "Mod Speed"               , "Reverb"      ,                   0.1f,                       4.0f,       1.0f, ParamScale::Linear, nullptr, const_cast<float *>(&gRevModSpeed), 1.0f },
    { 113, "revmoddepth"   , "Mod Depth"               , "Reverb"      ,                   0.0f,                       1.0f,       1.0f, ParamScale::Linear, nullptr, const_cast<float *>(&gRevModDepth), 1.0f },
    { 117, "revsize"       , "Size"                    , "Reverb"      ,                   0.0f,                       1.0f,       0.5f, ParamScale::Linear, nullptr, const_cast<float *>(&gRevSize), 1.0f },
    { 118, "revdamping"    , "Damping"                 , "Reverb"      ,                   0.0f,                       1.0f,       0.5f, ParamScale::Linear, nullptr, const_cast<float *>(&gRevDamping), 1.0f },
};
// clang-format on

static const uint8_t kParamManifestCount
    = sizeof(kParamManifest) / sizeof(kParamManifest[0]);

void paramHook_envelopeTypeChanged();
void paramHook_velocitySensitivityChanged();

// clang-format off
static const ParamOption kOpts_glide[] = {
    { "Off"                   ,   0,  63,   0 },
    { "On"                    ,  64, 127,   1 },
};
static const ParamOption kOpts_filtermode[] = {
    { "Off"                   ,   0,  25,   0 },
    { "LP"                    ,  26,  50,   1 },
    { "HP"                    ,  51,  76,   2 },
    { "BP"                    ,  77, 101,   3 },
    { "Notch"                 , 102, 127,   4 },
};
static const ParamOption kOpts_filtertype[] = {
    { "SVF"                   ,   0,  63,   0 },
    { "Ladder"                ,  64, 127,   1 },
};
static const ParamOption kOpts_fxfilterpos[] = {
    { "Pre-Chorus"            ,   0,  63,   0 },
    { "Post-Chorus"           ,  64, 127,   1 },
};
static const ParamOption kOpts_fxdelaypos[] = {
    { "Pre-Reverb"            ,   0,  63,   0 },
    { "Post-Reverb"           ,  64, 127,   1 },
};
static const ParamOption kOpts_envtype[] = {
    { "AR"                    ,   0,  63,   0 },
    { "ADSR"                  ,  64, 127,   1 },
};
static const ParamOption kOpts_suboct[] = {
    { "−1 Oct"                ,   0,  63,   1 },
    { "−2 Oct"                ,  64, 127,   2 },
};
static const ParamOption kOpts_chorusmode[] = {
    { "Off"                   ,   0,  31,   0 },
    { "I"                     ,  32,  63,   1 },
    { "II"                    ,  64,  95,   2 },
    { "I+II"                  ,  96, 127,   3 },
};
static const ParamOption kOpts_veloc[] = {
    { "Fixed"                 ,   0,  63,   0 },
    { "Velocity-sensitive"    ,  64, 127,   1 },
};
static const ParamOption kOpts_scale[] = {
    { "Chromatic (off)"       ,   0,   0,   0 },
    { "Major"                 ,   1,   1,   1 },
    { "Natural Minor"         ,   2,   2,   2 },
    { "Harmonic Minor"        ,   3,   3,   3 },
    { "Melodic Minor"         ,   4,   4,   4 },
    { "Pentatonic Maj"        ,   5,   5,   5 },
    { "Pentatonic Min"        ,   6,   6,   6 },
    { "Blues"                 ,   7,   7,   7 },
    { "Dorian"                ,   8,   8,   8 },
    { "Phrygian"              ,   9,   9,   9 },
    { "Lydian"                ,  10,  10,  10 },
    { "Mixolydian"            ,  11,  11,  11 },
    { "Locrian"               ,  12,  12,  12 },
    { "Whole Tone"            ,  13,  13,  13 },
    { "Diminished"            ,  14,  14,  14 },
};
static const ParamOption kOpts_mode[] = {
    { "Pair"                  ,   0,  20,   0 },
    { "Cloud"                 ,  21,  41,   1 },
    { "Chord"                 ,  42,  62,   2 },
    { "Cascade"               ,  63,  83,   3 },
    { "String"                ,  84, 104,   4 },
    { "Poly"                  , 105, 127,   5 },
};

static const EnumParamDescriptor kEnumManifest[] = {
    {  65, "glide"       , "Glide"                   , "Animation"   , (uint8_t *)&gGlideEnabled, kOpts_glide, sizeof(kOpts_glide) / sizeof(kOpts_glide[0]),   0, nullptr },
    {  76, "filtermode"  , "Mode"                    , "Filter"      , (uint8_t *)&gFilterMode, kOpts_filtermode, sizeof(kOpts_filtermode) / sizeof(kOpts_filtermode[0]),   0, nullptr },
    {  77, "filtertype"  , "Algorithm"               , "Filter"      , (uint8_t *)&gFilterType, kOpts_filtertype, sizeof(kOpts_filtertype) / sizeof(kOpts_filtertype[0]),   0, nullptr },
    {  79, "fxfilterpos" , "Filter Position"         , "FX Chain"    , (uint8_t *)&gFxOrder.filterPostChorus, kOpts_fxfilterpos, sizeof(kOpts_fxfilterpos) / sizeof(kOpts_fxfilterpos[0]),   0, nullptr },
    {  80, "fxdelaypos"  , "Delay Position"          , "FX Chain"    , (uint8_t *)&gFxOrder.delayPostReverb, kOpts_fxdelaypos, sizeof(kOpts_fxdelaypos) / sizeof(kOpts_fxdelaypos[0]),   0, nullptr },
    {  81, "envtype"     , "Type"                    , "Envelope"    , (uint8_t *)&gEnvelopeType, kOpts_envtype, sizeof(kOpts_envtype) / sizeof(kOpts_envtype[0]),   0, paramHook_envelopeTypeChanged },
    {  90, "suboct"      , "Sub Octave"              , "Oscillator"  , (uint8_t *)&gSubOctave, kOpts_suboct, sizeof(kOpts_suboct) / sizeof(kOpts_suboct[0]),   1, nullptr },
    {  93, "chorusmode"  , "Mode"                    , "Chorus"      , (uint8_t *)&gChorusMode, kOpts_chorusmode, sizeof(kOpts_chorusmode) / sizeof(kOpts_chorusmode[0]),   3, nullptr },
    { 102, "veloc"       , "MIDI Velocity Response"  , "Envelope"    , (uint8_t *)&gVelocitySensitive, kOpts_veloc, sizeof(kOpts_veloc) / sizeof(kOpts_veloc[0]),   1, paramHook_velocitySensitivityChanged },
    { 103, "scale"       , "Input Quantization"      , "Voice"       , (uint8_t *)&gQuantizeScale, kOpts_scale, sizeof(kOpts_scale) / sizeof(kOpts_scale[0]),   0, nullptr },
    { 115, "mode"        , "Voice Mode"              , "Voice"       , (uint8_t *)&gVoiceMode, kOpts_mode, sizeof(kOpts_mode) / sizeof(kOpts_mode[0]),   0, nullptr },
};
// clang-format on

static const uint8_t kEnumManifestCount
    = sizeof(kEnumManifest) / sizeof(kEnumManifest[0]);
