// GENERATED by tools/gen_params.py from modules/alloycoil/params.json — DO NOT EDIT BY HAND.
#pragma once

#include "ParamDescriptor.h"
#include "params.h"

// clang-format off
static const ParamDescriptor kParamManifest[] = {
    {   7, "vol"           , "Volume"                  , "Output"      ,                   0.0f,                       1.0f,       1.0f, ParamScale::Linear, nullptr, &gCoilParams.outputLevel, 2.0f, ParamDisplay::Direct },
    {  16, "pitch"         , "String Pitch"            , "Resonator"   ,                  16.0f,                      72.0f,      40.0f, ParamScale::Linear, "note", &gCoilParams.stringPitch, 1.0f, ParamDisplay::Direct },
    {  17, "fbgain"        , "Feedback Gain"           , "Feedback"    ,                 -30.0f,                      12.0f,     -30.0f, ParamScale::Linear, "dB"  , &gCoilParams.feedbackGain, 1.0f, ParamDisplay::Direct },
    {  18, "fbbody"        , "Body"                    , "Feedback"    ,                 0.001f,                       0.1f,     0.001f, ParamScale::Linear, "s"   , &gCoilParams.feedbackDelay, 2.0f, ParamDisplay::Direct },
    {  19, "excite"        , "Exciter Level"           , "Resonator"   ,                   0.0f,                       2.0f,       1.0f, ParamScale::Linear, "dB"  , &gCoilParams.exciterLevel, 2.0f, ParamDisplay::GainDb },
    {  74, "fblpf"         , "Feedback LPF"            , "Feedback"    ,                 100.0f,                   18000.0f,   18000.0f, ParamScale::Log , "Hz"  , &gCoilParams.feedbackLPF, 1.0f, ParamDisplay::Direct },
    {  75, "fbhpf"         , "Feedback HPF"            , "Feedback"    ,                  10.0f,                    4000.0f,     250.0f, ParamScale::Log , "Hz"  , &gCoilParams.feedbackHPF, 1.0f, ParamDisplay::Direct },
    {  86, "echotime"      , "Time"                    , "Echo"        ,                  0.05f,     (float)COIL_ECHO_MAX_S,       0.5f, ParamScale::Linear, "s"   , &gCoilParams.echoTime, 2.0f, ParamDisplay::Direct },
    {  87, "echofb"        , "Feedback"                , "Echo"        ,                   0.0f,                       1.2f,       0.0f, ParamScale::Linear, nullptr, &gCoilParams.echoFeedback, 1.0f, ParamDisplay::Direct },
    {  91, "revmix"        , "Dry/Wet"                 , "Reverb"      ,                   0.0f,                       1.0f,       0.0f, ParamScale::Linear, nullptr, &gCoilParams.reverbMix, 1.0f, ParamDisplay::Direct },
    {  92, "revdecay"      , "Decay"                   , "Reverb"      ,                   0.2f,                       1.0f,       0.2f, ParamScale::Linear, nullptr, &gCoilParams.reverbDecay, 0.5f, ParamDisplay::Direct },
    {  93, "echosend"      , "Send"                    , "Echo"        ,                   0.0f,                       1.0f,       0.0f, ParamScale::Linear, nullptr, &gCoilParams.echoSend, 2.0f, ParamDisplay::Direct },
};
// clang-format on

static const uint8_t kParamManifestCount
    = sizeof(kParamManifest) / sizeof(kParamManifest[0]);


// clang-format off
static const ParamOption kOpts_warp[] = {
    { "Off"                   ,   0,  63,   0 },
    { "On"                    ,  64, 127,   1 },
};

static const EnumParamDescriptor kEnumManifest[] = {
    {  20, "warp"        , "Warp"                    , "Echo"        , (uint8_t *)&gCoilParams.warp, kOpts_warp, sizeof(kOpts_warp) / sizeof(kOpts_warp[0]),   0, nullptr },
};
// clang-format on

static const uint8_t kEnumManifestCount
    = sizeof(kEnumManifest) / sizeof(kEnumManifest[0]);

/// Write every parameter's `default` from params.json into its target.
///
/// This is the runtime half of what the initialisers in
/// param_globals.generated.h do at static-init time: same column, same
/// targets. Preset "factory reset" paths call it instead of carrying their own
/// list of defaults.
static inline void applyParamDefaults()
{
    for(uint8_t i = 0; i < kParamManifestCount; i++)
        *kParamManifest[i].target = kParamManifest[i].defVal;
    for(uint8_t i = 0; i < kEnumManifestCount; i++)
        *kEnumManifest[i].target = kEnumManifest[i].defValue;
}
