// GENERATED by tools/gen_params.py from modules/alloycoil/params.json — DO NOT EDIT BY HAND.
#pragma once

#include "param_struct.generated.h"
#include "params.h"

// ---------------------------------------------------------------------------
// Definitions for the parameter storage declared in params.h, initialised to
// the `default` column of params.json.
//
// This header DEFINES objects, so include it in exactly one translation unit
// per binary — the firmware's main.cpp, the VCV module, the params test. They
// are static-initialised, so the values are already right before any code runs
// and no boot path has to remember to call applyParamDefaults(); that one is
// for factory reset, where the same table is applied at runtime.
// ---------------------------------------------------------------------------

/// The firmware's one instance. Hosts that run several copies of the
/// module own theirs instead and never touch this.
CoilParams gCoilParams;
