// GENERATED by tools/gen_params.py from modules/alloycoil/params.json — DO NOT EDIT BY HAND.
#pragma once

#include <stdint.h>

// ---------------------------------------------------------------------------
// Definitions for the parameter globals declared in params.h, initialised to
// the `default` column of params.json.
//
// This header DEFINES objects, so include it in exactly one translation unit
// per binary — the firmware's main.cpp, the VCV module, the params test. They
// are static-initialised, so the values are already right before any code runs
// and no boot path has to remember to call applyParamDefaults(); that one is
// for factory reset, where the same table is applied at runtime.
// ---------------------------------------------------------------------------

// clang-format off
float gStringPitch   = 40.0f;
float gFeedbackGain  = -30.0f;
float gExciterLevel  = 1.0f;
float gFeedbackDelay = 0.001f;
float gFeedbackLPF   = 18000.0f;
float gFeedbackHPF   = 250.0f;
float gEchoSend      = 0.0f;
float gEchoTime      = 0.5f;
float gEchoFeedback  = 0.0f;
uint8_t gWarp          = 0;
float gReverbMix     = 0.0f;
float gReverbDecay   = 0.2f;
float gOutputLevel   = 1.0f;
// clang-format on
