// GENERATED by tools/gen_params.py from modules/alloycoil/params.json — DO NOT EDIT BY HAND.
#pragma once

#include <stdint.h>

// ---------------------------------------------------------------------------
// CoilParamGoals — the `default` column of params.json, as a type.
//
// One of these is one instance's parameters. The firmware has exactly one and
// reaches it through the global in param_globals.generated.h; a host that can
// run several copies of the module gives each its own, which is the whole
// reason this is a struct and not a pile of globals.
//
// Declaring a type is safe anywhere, so unlike param_globals.generated.h this
// header may be included as widely as it likes.
// ---------------------------------------------------------------------------

// clang-format off
struct CoilParamGoals
{
    float   stringPitch   = 40.0f;
    float   feedbackGain  = -30.0f;
    float   exciterLevel  = 1.0f;
    float   feedbackDelay = 0.001f;
    float   feedbackLPF   = 18000.0f;
    float   feedbackHPF   = 250.0f;
    float   echoSend      = 0.0f;
    float   echoTime      = 0.5f;
    float   echoFeedback  = 0.0f;
    uint8_t warp          = 0;
    float   reverbMix     = 0.0f;
    float   reverbDecay   = 0.2f;
    float   outputLevel   = 1.0f;
};
// clang-format on
