// GENERATED by tools/gen_params.py from modules/alloycoil/params.json — DO NOT EDIT BY HAND.
#pragma once

#include "ParamDescriptor.h"
#include "params.h"

// clang-format off
static const ParamDescriptor kParamManifest[] = {
    {   7, "vol"           , "Volume"                  , "Output"      ,                   0.0f,                       1.0f,       0.5f, ParamScale::Linear, nullptr, &gOutputLevel, 2.0f },
    {  16, "pitch"         , "String Pitch"            , "Resonator"   ,                  16.0f,                      72.0f,      40.0f, ParamScale::Linear, "note", &gStringPitch, 1.0f },
    {  17, "fbgain"        , "Feedback Gain"           , "Feedback"    ,                 -30.0f,                      12.0f,     -30.0f, ParamScale::Linear, "dB"  , &gFeedbackGain, 1.0f },
    {  18, "fbbody"        , "Body"                    , "Feedback"    ,                 0.001f,                       0.1f,     0.001f, ParamScale::Linear, "s"   , &gFeedbackDelay, 2.0f },
    {  19, "excite"        , "Exciter Level"           , "Resonator"   ,                   0.0f,                       2.0f,       1.0f, ParamScale::Linear, nullptr, &gExciterLevel, 2.0f },
    {  74, "fblpf"         , "Feedback LPF"            , "Feedback"    ,                 100.0f,                   18000.0f,   18000.0f, ParamScale::Log , "Hz"  , &gFeedbackLPF, 1.0f },
    {  75, "fbhpf"         , "Feedback HPF"            , "Feedback"    ,                  10.0f,                    4000.0f,     250.0f, ParamScale::Log , "Hz"  , &gFeedbackHPF, 1.0f },
    {  86, "echotime"      , "Time"                    , "Echo"        ,                  0.05f,     (float)COIL_ECHO_MAX_S,       0.5f, ParamScale::Linear, "s"   , &gEchoTime, 2.0f },
    {  87, "echofb"        , "Feedback"                , "Echo"        ,                   0.0f,                       1.2f,       0.0f, ParamScale::Linear, nullptr, &gEchoFeedback, 1.0f },
    {  91, "revmix"        , "Mix"                     , "Reverb"      ,                   0.0f,                       1.0f,       0.0f, ParamScale::Linear, nullptr, &gReverbMix, 1.0f },
    {  92, "revdecay"      , "Decay"                   , "Reverb"      ,                   0.2f,                       1.0f,       0.2f, ParamScale::Linear, nullptr, &gReverbDecay, 0.5f },
    {  93, "echosend"      , "Send"                    , "Echo"        ,                   0.0f,                       1.0f,       0.0f, ParamScale::Linear, nullptr, &gEchoSend, 2.0f },
};
// clang-format on

static const uint8_t kParamManifestCount
    = sizeof(kParamManifest) / sizeof(kParamManifest[0]);

// clang-format off

// No discrete parameters in this module.
static const EnumParamDescriptor *const kEnumManifest = nullptr;
// clang-format on

static const uint8_t kEnumManifestCount = 0;
