import type { CapacitorConfig } from "@capacitor/cli";

/**
 * The native shell — Milestone 80.
 *
 * Capacitor wraps the *same* `dist/` that `make web` produces in a WKWebView
 * (iOS) or a WebView (Android) and hands it a bridge to native APIs. There is
 * no second codebase and no second UI: the only thing the shell changes is
 * which implementation `lib/bleLink.ts` picks, and that decision is made at
 * runtime from a global the bridge sets before any app code runs.
 *
 * **Why this exists at all is iOS.** Android already works fine in Chrome —
 * Web Bluetooth is there, the PWA installs, and the app is a distribution
 * convenience rather than a capability. iOS is the opposite: WebKit ships no
 * Web Bluetooth, no Web MIDI and no Web Serial, an installed PWA on iOS is
 * still WebKit, and so the app is the *only* way a page can reach a module
 * from an iPhone. Android is built alongside because it costs one extra
 * command once the BLE adapter exists.
 *
 * ⚠ **`appId` is permanent.** Apple and Google both key an app's identity to
 * it, and neither lets you change it after the first submission without
 * shipping what users see as a different app. Change it here before the first
 * `npx cap sync`, or not at all.
 *
 * Workflow — the Makefile wraps all of this:
 *
 *   make web            build dist/            (must run before any sync)
 *   make app-sync       copy dist/ into both native projects
 *   make app-ios        open Xcode
 *   make app-android    open Android Studio
 *
 * `ios/` and `android/` are generated by `npx cap add` and are **committed**,
 * because they hold the signing config, the Info.plist permission strings and
 * the icon sets — regenerating them would silently drop all three.
 */
const config: CapacitorConfig = {
  appId: "com.voltagefoundry.alloycontroller",
  appName: "Alloy Controller",
  webDir: "dist",

  // The page is a dark instrument panel. Without these the WebView paints
  // white behind it during launch and on rubber-band overscroll, which on a
  // phone reads as a flash of a broken page. Matches --bg in app.css.
  backgroundColor: "#131518",

  ios: {
    backgroundColor: "#131518",
    // The panel manages its own scrolling and the keyboard is only used by the
    // preset name field; `always` keeps the content clear of the notch and the
    // home indicator without the layout jumping when the keyboard appears.
    contentInset: "always",
  },

  android: {
    backgroundColor: "#131518",
    // Secure-context APIs are still checked inside the WebView, and a plain
    // `http://` origin would define none of them — the same trap `make
    // web-host` exists to avoid on the LAN.
    allowMixedContent: false,
  },

  server: {
    androidScheme: "https",
  },

  plugins: {
    // Shown in the plugin's own device-chooser dialog. Worth setting: the
    // defaults say "Bluetooth device", which is unhelpfully generic in a room
    // that may also contain speakers, watches and a car.
    BluetoothLe: {
      displayStrings: {
        scanning: "Looking for modules…",
        cancel: "Cancel",
        availableDevices: "Modules found",
        noDeviceFound: "No module found. Check it is powered and advertising.",
      },
    },
  },
};

export default config;
