#pragma once

// GENERATED by tools/svg_path_to_nvg.py — do not edit.
//   source : panel-src/AlloyCoil_src.svg
//   path   : LED1
//
// Regenerate with:  make led-shape
//
// Coordinates are millimetres, bounding box normalised to the origin, so a
// widget scales this to its own box.size. See platform/vcv/PanelLed.hpp.

#include <nanovg.h>

namespace AlloyPanelLed
{

/// Bounding box of the shape as drawn on the panel, in mm.
static constexpr float kWidthMm  = 3.9884f;
static constexpr float kHeightMm = 3.9998f;

/// Emits the outline into the current NanoVG path. Call between nvgBeginPath()
/// and nvgFill(); scale first if the widget is not exactly kWidthMm wide.
inline void path(NVGcontext *vg)
{
    nvgMoveTo(vg, 1.9942f, 0.0000f);
    nvgBezierTo(vg, 1.3308f, 0.0000f, 0.7106f, 0.3289f, 0.3385f, 0.8780f);
    nvgLineTo(vg, 1.5069f, 0.8780f);
    nvgBezierTo(vg, 1.6227f, 0.8780f, 1.7157f, 0.9457f, 1.7157f, 1.0299f);
    nvgBezierTo(vg, 1.7157f, 1.1141f, 1.6227f, 1.1818f, 1.5069f, 1.1818f);
    nvgLineTo(vg, 0.1690f, 1.1818f);
    nvgBezierTo(vg, 0.0745f, 1.3928f, 0.0174f, 1.6185f, 0.0000f, 1.8490f);
    nvgBezierTo(vg, 0.0053f, 1.8487f, 0.0106f, 1.8485f, 0.0160f, 1.8485f);
    nvgLineTo(vg, 1.5157f, 1.8485f);
    nvgBezierTo(vg, 1.6315f, 1.8485f, 1.7244f, 1.9162f, 1.7244f, 2.0004f);
    nvgBezierTo(vg, 1.7244f, 2.0846f, 1.6315f, 2.1523f, 1.5157f, 2.1523f);
    nvgLineTo(vg, 0.0160f, 2.1523f);
    nvgBezierTo(vg, 0.0106f, 2.1523f, 0.0053f, 2.1521f, 0.0000f, 2.1518f);
    nvgBezierTo(vg, 0.0175f, 2.3823f, 0.0749f, 2.6080f, 0.1695f, 2.8189f);
    nvgLineTo(vg, 1.5301f, 2.8189f);
    nvgBezierTo(vg, 1.6460f, 2.8189f, 1.7394f, 2.8867f, 1.7394f, 2.9709f);
    nvgBezierTo(vg, 1.7394f, 3.0551f, 1.6460f, 3.1228f, 1.5301f, 3.1228f);
    nvgLineTo(vg, 0.3395f, 3.1228f);
    nvgBezierTo(vg, 0.7117f, 3.6712f, 1.3314f, 3.9997f, 1.9942f, 3.9998f);
    nvgBezierTo(vg, 2.6570f, 3.9997f, 3.2767f, 3.6712f, 3.6489f, 3.1228f);
    nvgLineTo(vg, 2.4877f, 3.1228f);
    nvgBezierTo(vg, 2.3715f, 3.1228f, 2.2779f, 3.0551f, 2.2779f, 2.9709f);
    nvgBezierTo(vg, 2.2779f, 2.8867f, 2.3715f, 2.8189f, 2.4877f, 2.8189f);
    nvgLineTo(vg, 3.8189f, 2.8189f);
    nvgBezierTo(vg, 3.9135f, 2.6082f, 3.9708f, 2.3827f, 3.9884f, 2.1523f);
    nvgBezierTo(vg, 3.9848f, 2.1525f, 3.9812f, 2.1523f, 3.9775f, 2.1523f);
    nvgLineTo(vg, 2.4732f, 2.1523f);
    nvgBezierTo(vg, 2.3570f, 2.1523f, 2.2634f, 2.0846f, 2.2634f, 2.0004f);
    nvgBezierTo(vg, 2.2634f, 1.9162f, 2.3570f, 1.8485f, 2.4732f, 1.8485f);
    nvgLineTo(vg, 3.9775f, 1.8485f);
    nvgBezierTo(vg, 3.9812f, 1.8485f, 3.9848f, 1.8483f, 3.9884f, 1.8485f);
    nvgBezierTo(vg, 3.9708f, 1.6181f, 3.9135f, 1.3926f, 3.8189f, 1.1818f);
    nvgLineTo(vg, 2.4644f, 1.1818f);
    nvgBezierTo(vg, 2.3483f, 1.1818f, 2.2546f, 1.1141f, 2.2546f, 1.0299f);
    nvgBezierTo(vg, 2.2546f, 0.9457f, 2.3483f, 0.8780f, 2.4644f, 0.8780f);
    nvgLineTo(vg, 3.6494f, 0.8780f);
    nvgBezierTo(vg, 3.2773f, 0.3290f, 2.6574f, 0.0001f, 1.9942f, 0.0000f);
    nvgClosePath(vg);
}

} // namespace AlloyPanelLed
