#pragma once

#include "PanelLedShape.generated.h"
#include <rack.hpp>

// ---------------------------------------------------------------------------
// AlloyPanelLight — a light widget shaped like the hole it shines through.
//
// On the hardware the panel *is* a PCB, and the LED apertures are openings in
// the front solder mask (the `F.Mask` layer of the panel drawing). The LED sits
// behind the board and its light comes through the bare FR4, which is
// translucent and the colour of weak tea: the result is a soft, slightly warm
// glow in the shape of the opening, with the slots reading as brighter lines
// rather than as hard edges.
//
// Rack's stock lights are circles with a circular halo, so using them here would
// draw a panel that does not match the module. This does three things instead:
//
//   * the outline comes from the panel artwork itself, generated by
//     tools/svg_path_to_nvg.py rather than transcribed;
//   * the unlit state is drawn as bare substrate, not as a dark grey LED can,
//     because that is what an unlit aperture actually looks like;
//   * the halo is wider and softer than Rack's default, which is the closest a
//     radial gradient gets to light scattering inside 1.6 mm of fibreglass.
//
// TBase is a colour trait, exactly as with Rack's own lights, so this composes
// the usual way:  AlloyPanelLight<RedGreenBlueLight>.
// ---------------------------------------------------------------------------

template <typename TBase = rack::componentlibrary::GrayModuleLightWidget>
struct AlloyPanelLight : TBase
{
    /// Halo extent as a multiple of the aperture's half-diagonal. Rack's own
    /// lights use a much tighter figure; light spreading sideways through the
    /// substrate carries further than light leaving a domed LED, and the panel
    /// looks wrong when the glow stops at the edge of the hole.
    float haloSpread = 3.0f;

    /// Colour of unlit bare FR4 seen through the mask opening. Warmer and
    /// lighter than the panel around it, which is what makes the apertures
    /// visible when the module is powered down.
    NVGcolor substrateColor = nvgRGB(0x3a, 0x35, 0x2c);

    AlloyPanelLight()
    {
        this->box.size = rack::mm2px(rack::math::Vec(AlloyPanelLed::kWidthMm,
                                                     AlloyPanelLed::kHeightMm));
        // The stock grey disc and its border belong to a moulded LED, not to a
        // hole. Both are replaced by drawBackground() below.
        this->bgColor     = rack::color::BLACK_TRANSPARENT;
        this->borderColor = rack::color::BLACK_TRANSPARENT;
    }

    /// Builds the aperture outline in widget-local pixels.
    ///
    /// NanoVG bakes the current transform into each point as the path is built,
    /// so the scale has to be set *before* the path calls and matters not at
    /// all afterwards — which is why the fill can safely happen after restore.
    void buildPath(NVGcontext *vg)
    {
        nvgSave(vg);
        nvgScale(vg,
                 this->box.size.x / AlloyPanelLed::kWidthMm,
                 this->box.size.y / AlloyPanelLed::kHeightMm);
        nvgBeginPath(vg);
        AlloyPanelLed::path(vg);
        nvgRestore(vg);
    }

    void drawBackground(const rack::widget::Widget::DrawArgs &args) override
    {
        buildPath(args.vg);
        nvgFillColor(args.vg, substrateColor);
        nvgFill(args.vg);
    }

    void drawLight(const rack::widget::Widget::DrawArgs &args) override
    {
        if(this->color.a <= 0.0f)
            return;
        buildPath(args.vg);
        nvgFillColor(args.vg, this->color);
        nvgFill(args.vg);
    }

    void drawHalo(const rack::widget::Widget::DrawArgs &args) override
    {
        // Adapted from LightWidget::drawHalo(). Skipped inside a framebuffer:
        // a halo drawn there would be cached and would not follow the light.
        if(args.fb)
            return;
        const float brightness = rack::settings::haloBrightness;
        if(brightness <= 0.0f || this->color.a <= 0.0f)
            return;

        const float cx = this->box.size.x * 0.5f;
        const float cy = this->box.size.y * 0.5f;
        const float r  = std::hypot(cx, cy) * haloSpread;

        NVGcolor icol = rack::color::mult(this->color, brightness);
        NVGcolor ocol = nvgRGBA(0, 0, 0, 0);

        nvgBeginPath(args.vg);
        nvgRect(args.vg, cx - r, cy - r, 2 * r, 2 * r);
        nvgFillPaint(args.vg,
                     nvgRadialGradient(args.vg, cx, cy, 0.0f, r, icol, ocol));
        nvgFill(args.vg);
    }
};
