#!/usr/bin/env python3
"""Generate parameter tables from a module's params.json.

A parameter used to be declared in up to ten places — the CC table, the serial
command, two halves of the config store, the SysEx dump, the VCV param list and
the web UI map — with three separate "adding a new parameter" checklists that
did not agree with each other. This generator makes params.json the only place
a parameter is described, and emits the rest.

Usage:  python tools/gen_params.py modules/alloyflux
        python tools/gen_params.py modules/alloyflux --list-outputs
Outputs (committed, so a normal build never needs Python):
    <module>/include/param_manifest.generated.h
    <module>/include/param_struct.generated.h    (only with "struct_output")
    <module>/include/param_globals.generated.h   (only with "globals_output")
    the path named by "ts_output"
    the path named by "md_output"  (spliced between markers, not overwritten)

A module chooses where its parameters live by how it writes `target`. A bare
identifier (`gMotion`) is a free-standing global, which is what a firmware-only
module wants. A member expression (`gCoilParams.echoTime`) says the parameters
are fields of a struct, and "struct_output" then generates that struct's type —
so a host that needs more than one copy of the module, which is every host that
is not the board, can give each instance its own set instead of sharing one.
"""

import json
import math
import os
import pathlib
import sys

BANNER = "// GENERATED by tools/gen_params.py from {src} — DO NOT EDIT BY HAND.\n"

# Factory reset, off the tables above rather than off a fourth hand-kept copy
# of the same numbers. `static` because the manifests have internal linkage —
# an `inline` function reading them would be a different definition per TU.
DEFAULTS_FN = """
/// Write every parameter's `default` from params.json into its target.
///
/// This is the runtime half of what the initialisers in
/// param_globals.generated.h do at static-init time: same column, same
/// targets. Preset "factory reset" paths call it instead of carrying their own
/// list of defaults.
static inline void applyParamDefaults()
{
    for(uint8_t i = 0; i < kParamManifestCount; i++)
        *kParamManifest[i].target = kParamManifest[i].defVal;
    for(uint8_t i = 0; i < kEnumManifestCount; i++)
        *kEnumManifest[i].target = kEnumManifest[i].defValue;
}
"""


def fmt_float(v):
    """C++ float literal. Accepts a number or {symbol, value}."""
    if isinstance(v, dict):
        return "(float)" + v["symbol"]
    return f"{v!r}f" if "." in repr(v) or "e" in repr(v) else f"{v}.0f"


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"' if s else "nullptr"


# `displayTransform` changes the number a UI prints without touching the stored
# value, the CC, or the curve. Deliberately not folded into the existing
# `display` block: that one re-parameterises a control over the same travel and
# only handles mappings a min/max pair can express. See ParamDisplay.
DISPLAY_TRANSFORMS = {"gain-db": "ParamDisplay::GainDb"}


def cpp_display(p):
    t = p.get("displayTransform")
    if t is None:
        return "ParamDisplay::Direct"
    if t not in DISPLAY_TRANSFORMS:
        sys.exit(f"{p['name']}: unknown displayTransform {t!r}")
    return DISPLAY_TRANSFORMS[t]


def gen_cpp(spec, src):
    params = [p for p in spec["params"] if p["kind"] == "float"]
    params.sort(key=lambda p: p["cc"])

    out = [BANNER.format(src=src), "#pragma once\n\n"]
    out.append('#include "ParamDescriptor.h"\n')
    for inc in spec.get("cpp_includes", []):
        out.append(f'#include "{inc}"\n')
    out.append("\n")
    out.append("// clang-format off\n")
    out.append("static const ParamDescriptor kParamManifest[] = {\n")
    for p in params:
        target = p["target"]
        # Some targets are declared volatile; the dispatcher writes through a
        # plain float* so those need the qualifier cast away at table build.
        addr = f"const_cast<float *>(&{target})" if p.get("volatile") else f"&{target}"
        out.append(
            "    {{ {cc:3}, {name:<16}, {label:<26}, {cat:<14}, "
            "{mn:>22}, {mx:>26}, {df:>10}, {scale:<16}, {unit:<6}, {addr}, "
            "{skew}, {disp} }},\n".format(
                cc=p["cc"],
                name=cstr(p["name"]),
                label=cstr(p["label"]),
                cat=cstr(p["category"]),
                mn=fmt_float(p["min"]),
                mx=fmt_float(p["max"]),
                df=fmt_float(p["default"]),
                scale="ParamScale::Log" if p.get("scale") == "log" else "ParamScale::Linear",
                unit=cstr(p.get("unit", "")),
                addr=addr,
                skew=fmt_float(p.get("skew", 1.0)),
                disp=cpp_display(p),
            )
        )
    out.append("};\n")
    out.append("// clang-format on\n\n")
    out.append(
        "static const uint8_t kParamManifestCount\n"
        "    = sizeof(kParamManifest) / sizeof(kParamManifest[0]);\n\n"
    )

    enums = [p for p in spec["params"] if p["kind"] == "enum"]
    enums.sort(key=lambda p: p["cc"])

    for h in sorted({p["onChange"] for p in enums if p.get("onChange")}):
        out.append(f"void {h}();\n")
    if enums:
        out.append("\n")

    out.append("// clang-format off\n")
    for p in enums:
        out.append(f"static const ParamOption kOpts_{p['name']}[] = {{\n")
        for o in p["options"]:
            out.append(
                "    {{ {label:<24}, {mn:3}, {mx:3}, {val:3} }},\n".format(
                    label=cstr(o["label"]), mn=o["ccMin"], mx=o["ccMax"], val=o["value"]
                )
            )
        out.append("};\n")
    if not enums:
        # A module may have no discrete parameters at all. `T x[] = {}` is a
        # GCC extension, not ISO C++, so emit a null pointer instead — the
        # consuming code only ever indexes it under `i < count`, and count is
        # zero. Same shape as the array case, so nothing downstream branches.
        out.append(
            "\n// No discrete parameters in this module.\n"
            "static const EnumParamDescriptor *const kEnumManifest = nullptr;\n"
        )
        out.append("// clang-format on\n\n")
        out.append("static const uint8_t kEnumManifestCount = 0;\n")
        out.append(DEFAULTS_FN)
        return "".join(out)

    out.append("\nstatic const EnumParamDescriptor kEnumManifest[] = {\n")
    for p in enums:
        out.append(
            "    {{ {cc:3}, {name:<14}, {label:<26}, {cat:<14}, "
            "(uint8_t *)&{target}, kOpts_{n}, "
            "sizeof(kOpts_{n}) / sizeof(kOpts_{n}[0]), {df:3}, {hook} }},\n".format(
                cc=p["cc"],
                name=cstr(p["name"]),
                label=cstr(p["label"]),
                cat=cstr(p["category"]),
                target=p["target"],
                n=p["name"],
                df=p["default"],
                hook=p.get("onChange") or "nullptr",
            )
        )
    out.append("};\n")
    out.append("// clang-format on\n\n")
    out.append(
        "static const uint8_t kEnumManifestCount\n"
        "    = sizeof(kEnumManifest) / sizeof(kEnumManifest[0]);\n"
    )
    out.append(DEFAULTS_FN)
    return "".join(out)


def split_target(name, target):
    """`target` as (owner, field). owner is "" for a free-standing global.

    The whole distinction between a module whose parameters are shared and one
    whose parameters are per-instance is carried in this one column, so a
    malformed target is worth stopping on rather than emitting code that will
    fail somewhere less obvious.
    """
    owner, _, field = target.rpartition(".")
    if not field.isidentifier() or (owner and not all(
        part.isidentifier() for part in owner.split(".")
    )):
        sys.exit(
            f"{name}: target {target!r} must be an identifier or a chain of "
            "them (`gCoilParams.echoTime`)"
        )
    return owner, field


def ctype_of(p):
    """The C++ type a parameter's storage is declared with."""
    if p["kind"] == "float":
        return "volatile float" if p.get("volatile") else "float"
    return p.get("ctype", "uint8_t")


def value_of(p):
    """The parameter's `default` as a C++ initialiser."""
    return fmt_float(p["default"]) if p["kind"] == "float" else p["default"]


def gen_struct(spec, src):
    """Emit the struct that holds one instance's worth of parameters.

    Only the type — the object itself is gen_globals()' job, because a type is
    safe in every translation unit and an object is not.

    Members are initialised to the `default` column, so a freshly constructed
    instance is already a valid patch: a host that creates one per voice, per
    module or per test does not have to remember to seed it, and cannot seed it
    with a copy of the numbers that has drifted from params.json.
    """
    cfg = spec["struct_output"]
    name = cfg["name"]
    fields = []
    for p in spec["params"]:
        owner, field = split_target(p["name"], p["target"])
        if not owner:
            sys.exit(
                f"struct_output: {p['name']}'s target {p['target']!r} is a bare "
                "global, so it cannot be a member of " + name
            )
        fields.append((ctype_of(p), field, value_of(p), p["name"]))

    tw = max(len(f[0]) for f in fields)
    nw = max(len(f[1]) for f in fields)
    lines = [
        BANNER.format(src=src),
        "#pragma once\n\n",
        "#include <stdint.h>\n\n",
        "// ---------------------------------------------------------------------------\n"
        f"// {name} — the `default` column of params.json, as a type.\n"
        "//\n"
        "// One of these is one instance's parameters. The firmware has exactly one and\n"
        "// reaches it through the global in param_globals.generated.h; a host that can\n"
        "// run several copies of the module gives each its own, which is the whole\n"
        "// reason this is a struct and not a pile of globals.\n"
        "//\n"
        "// Declaring a type is safe anywhere, so unlike param_globals.generated.h this\n"
        "// header may be included as widely as it likes.\n"
        "// ---------------------------------------------------------------------------\n\n",
        "// clang-format off\n",
        f"struct {name}\n{{\n",
    ]
    for ctype, field, value, _ in fields:
        lines.append(f"    {ctype:<{tw}} {field:<{nw}} = {value};\n")
    lines.append("};\n")
    lines.append("// clang-format on\n")
    return "".join(lines)


def gen_globals(spec, src):
    """Emit the definition of the module's parameter storage.

    The manifest's `target` column already names the lvalue every transport
    writes; this makes params.json own its *starting* value too. Without it the
    same twelve numbers are typed out once per binary that links them —
    firmware, VCV module, host test — and editing params.json moves the CC
    range and the web slider while leaving all three boot values behind.

    With "struct_output" this is one object of that struct; without it, one
    global per row, which is the older shape and still what a firmware-only
    module wants.
    """
    lines = [
        BANNER.format(src=src),
        "#pragma once\n\n",
    ]
    struct = spec.get("struct_output")
    if struct:
        lines.append(f'#include "{struct["header"]}"\n')
        lines.append('#include "params.h"\n\n')
    else:
        lines.append("#include <stdint.h>\n\n")
    lines.append(
        "// ---------------------------------------------------------------------------\n"
        "// Definitions for the parameter storage declared in params.h, initialised to\n"
        "// the `default` column of params.json.\n"
        "//\n"
        "// This header DEFINES objects, so include it in exactly one translation unit\n"
        "// per binary — the firmware's main.cpp, the VCV module, the params test. They\n"
        "// are static-initialised, so the values are already right before any code runs\n"
        "// and no boot path has to remember to call applyParamDefaults(); that one is\n"
        "// for factory reset, where the same table is applied at runtime.\n"
        "// ---------------------------------------------------------------------------\n\n"
    )

    if struct:
        owners = {split_target(p["name"], p["target"])[0] for p in spec["params"]}
        if owners != {struct["instance"]}:
            sys.exit(
                "struct_output: every target must be a member of "
                f"{struct['instance']}, found {sorted(owners)}"
            )
        lines.append(
            f"/// The firmware's one instance. Hosts that run several copies of the\n"
            f"/// module own theirs instead and never touch this.\n"
            f"{struct['type']} {struct['instance']};\n"
        )
        return "".join(lines)

    lines.append("// clang-format off\n")
    width = max(len(p["target"]) for p in spec["params"])
    for p in spec["params"]:
        owner, _ = split_target(p["name"], p["target"])
        if owner:
            sys.exit(
                f"globals_output: {p['name']}'s target {p['target']!r} names a "
                "member, which needs \"struct_output\" to declare its type"
            )
        lines.append(f"{ctype_of(p)} {p['target']:<{width}} = {value_of(p)};\n")
    lines.append("// clang-format on\n")
    return "".join(lines)


def num_of(v):
    """A bound may be a plain number or a {symbol, value} pair."""
    return v["value"] if isinstance(v, dict) else v


def to_pos(p, value):
    """Value → control position 0–1. Mirrors ParamDescriptor::toPos()."""
    lo, hi = num_of(p["min"]), num_of(p["max"])
    if p.get("scale") == "log":
        if lo <= 0 or value <= 0:
            sys.exit(f"{p['name']}: log scale needs a positive min and default")
        t = math.log(value / lo) / math.log(hi / lo)
    else:
        t = (value - lo) / (hi - lo)
    t = min(max(t, 0.0), 1.0)
    skew = p.get("skew", 1.0)
    return t ** (1.0 / skew) if skew != 1 else t


def from_pos(p, t):
    """Control position 0–1 → value. Mirrors ParamDescriptor::fromPos()."""
    lo, hi = num_of(p["min"]), num_of(p["max"])
    skew = p.get("skew", 1.0)
    if skew != 1 and t > 0:
        t = t**skew
    if p.get("scale") == "log":
        return lo * (hi / lo) ** t
    return lo + t * (hi - lo)


def display_default(p, disp):
    """The `default` a display-re-parameterised slider should boot to.

    `display` restates a parameter over the same travel in different units, so
    the honest default is the stored one carried across at equal control
    position — not a number typed a second time, and emphatically not 0.

    This used to emit `displayDefault` or fall back to 0. Only `root` had a
    display block and 0 is right for root purely by luck: 440 Hz is the middle
    of its 8-octave sweep and its display range is ±48 semitones centred on the
    same point. Any other parameter given a display block booted the web UI to
    0 — for Alloy Coil's Body, below its own minimum.
    """
    if "displayDefault" in p:  # explicit override still wins
        return p["displayDefault"]
    merged = {**p, **disp}
    v = round(from_pos(merged, to_pos(p, p["default"])), 6)
    # Emit a whole number as an int, so a derived default that lands on one
    # renders as `0` rather than `0.0` — the literal the hand-written fallback
    # produced, and the one a reader of the map expects.
    return int(v) if float(v).is_integer() else v


def gen_ts(spec, src):
    """Emit the web configurator's parameter map."""
    out = [
        BANNER.format(src=src).replace("//", "//", 1),
        "\n",
        'import type { CCParam } from "./paramMapTypes";\n',
        'export type { CCParam, ParamType, SelectOption } from "./paramMapTypes";\n',
        'export { ccToFloat, floatToCC } from "./paramMapTypes";\n\n',
        "export const PARAM_CATEGORIES = [\n",
    ]
    for c in spec["categories"]:
        out.append(f'  "{c}",\n')
    out.append("] as const;\n\n")
    out.append("export type ParamCategory = (typeof PARAM_CATEGORIES)[number];\n\n")
    out.append("export const PARAM_MAP: CCParam[] = [\n")

    def num(v):
        if isinstance(v, dict):
            return repr(v["value"])
        return repr(v)

    # Authoring order, not CC order: the UI lays parameters out in the sequence
    # they appear in params.json, and that sequence is curated (Mix before Time
    # before Feedback, ADSR after the envelope selectors, and so on). Sorting
    # here would scatter them. The C++ table sorts by CC independently, where
    # order is only a lookup detail.
    for p in spec["params"]:
        out.append("  {\n")
        out.append(f'    cc: {p["cc"]},\n')
        out.append(f'    name: "{p["name"]}",\n')
        out.append(f'    label: "{p["label"]}",\n')
        out.append(f'    category: "{p["category"]}",\n')
        if p["kind"] in ("float", "special"):
            # `display` lets a parameter present in different units from the
            # ones the firmware stores. The CC sent is unchanged either way —
            # only the number next to the slider differs. Used by root, which
            # the module keeps in Hz but which reads far better as semitones.
            d = {**p, **p.get("display", {})}
            out.append(f'    min: {num(d["min"])},\n')
            out.append(f'    max: {num(d["max"])},\n')
            default = (
                p["default"]
                if "display" not in p
                else display_default(p, p["display"])
            )
            out.append(f'    default: {num(default)},\n')
            if d.get("unit"):
                out.append(f'    unit: "{d["unit"]}",\n')
            if d.get("scale") == "log":
                out.append('    scale: "log",\n')
            if d.get("skew") is not None and float(d["skew"]) != 1.0:
                out.append(f'    skew: {num(d["skew"])},\n')
            if d.get("step") is not None:
                out.append(f'    step: {d["step"]},\n')
            if d.get("ccRange"):
                out.append(
                    f'    ccRange: {{ min: {d["ccRange"]["min"]}, max: {d["ccRange"]["max"]} }},\n'
                )
            if d.get("displayTransform"):
                out.append(f'    displayTransform: "{d["displayTransform"]}",\n')
        else:
            out.append("    min: 0,\n    max: 127,\n")
            # The web map's `default` is a raw CC value, but params.json's is the
            # *stored* value the C++ target boots to — so it has to be resolved
            # through the option table rather than passed straight through. This
            # used to emit options[0].ccMin unconditionally, which is only right
            # when the default happens to be the first option: the web UI showed
            # Chorus "Off" and velocity "Fixed" while the firmware booted to
            # I+II and velocity-sensitive.
            opt = next((o for o in p["options"] if o["value"] == p["default"]), None)
            if opt is None:
                sys.exit(
                    f"{p['name']}: default {p['default']!r} matches no option value"
                )
            out.append(f'    default: {opt["ccMin"]},\n')
            out.append('    type: "select",\n')
            out.append("    options: [\n")
            for o in p["options"]:
                out.append(
                    f'      {{ label: "{o["label"]}", ccMin: {o["ccMin"]}, ccMax: {o["ccMax"]} }},\n'
                )
            out.append("    ],\n")
        out.append("  },\n")
    out.append("];\n\n")
    out.append(
        "export const PARAMS_BY_CATEGORY = Object.fromEntries(\n"
        "  PARAM_CATEGORIES.map((c) => [c, PARAM_MAP.filter((p) => p.category === c)]),\n"
        ") as Record<ParamCategory, CCParam[]>;\n"
    )
    return "".join(out)


# The MANUAL's CC map used to be typed out by hand, which is how it came to
# call CC 92 "FM" long after params.json, the firmware and the web UI had all
# settled on "Color". Only the prose is authored now (the `doc` field); every
# number in the table below is derived from the same columns the C++ and
# TypeScript tables are built from, so the three cannot disagree.
MD_BEGIN = "<!-- BEGIN GENERATED: cc-map — `make params`, do not edit by hand -->"
MD_END = "<!-- END GENERATED: cc-map -->"


# Units that read as a symbol attached to the number ("4×") rather than as a
# word after it ("4 s").
TIGHT_UNITS = {"×", "%", "°"}


def fmt_num(v):
    """Render a JSON number the way a reader wants it, not the way repr does."""
    if isinstance(v, dict):
        v = v["value"]
    if isinstance(v, float) and v.is_integer():
        v = int(v)
    # A real minus sign, so a negative bound cannot be misread as the dash that
    # separates the two bounds. No thousands separator: these are engineering
    # values and "16,000 Hz" invites a decimal-comma misreading.
    return str(v).replace("-", "−")


def md_range(p):
    """The CC-side range — what a controller actually sends."""
    if p["kind"] == "enum":
        # A band one CC wide is a value, not a range: the 15-entry quantizer
        # table renders as "0 = Chromatic", not "0–0 = Chromatic".
        return " · ".join(
            (f"{o['ccMin']}" if o["ccMin"] == o["ccMax"] else f"{o['ccMin']}–{o['ccMax']}")
            + f" = {o['label']}"
            for o in p["options"]
        )
    cr = p.get("ccRange")
    return f"{cr['min']}–{cr['max']}" if cr else "0–127"


def to_display(v, transform):
    """Mirror of ParamDescriptor::toDisplay — the stored value is not always
    the number a reader should see. Kept in step with ParamDescriptor.h."""
    if transform == "gain-db":
        if isinstance(v, dict):
            v = v["value"]
        # 20·log10(0) is −inf, which is the honest bottom of a gain taper.
        return "−∞" if v <= 0 else round(20.0 * math.log10(v), 1)
    return v


def md_value(p):
    """The engineering range, in the units the reader thinks in."""
    if p["kind"] == "enum":
        return ""
    d = {**p, **p.get("display", {})}
    if d.get("min") is None or d.get("max") is None:
        return ""
    xform = d.get("displayTransform")
    lo, hi = fmt_num(to_display(d["min"], xform)), fmt_num(to_display(d["max"], xform))
    # An en dash between a negative bound and its partner is unreadable
    # ("−24–24"), so a signed range gets an ellipsis and an explicit "+".
    if lo.startswith("−"):
        span = f"{lo} … +{hi}" if not hi.startswith("−") else f"{lo} … {hi}"
    else:
        span = f"{lo}–{hi}"
    unit = d.get("unit", "")
    if unit:
        span += unit if unit in TIGHT_UNITS else f" {unit}"
    if d.get("scale") == "log":
        span += ", log"
    return span


def md_width(cell):
    """Display width of a table cell. Every character these tables use — en
    dashes, the minus sign, ×, · — is single-width, so this is just len()."""
    return len(cell)


def md_row(cells, width):
    return "| " + " | ".join(c.ljust(w) for c, w in zip(cells, width)) + " |\n"


def gen_md(spec, src, existing):
    """Splice the CC map into the module's manual, between the markers.

    Unlike the other emitters this one does not own its whole file — the manual
    is hand-written prose around one generated table — so it edits in place and
    leaves everything outside the markers alone.
    """
    if MD_BEGIN not in existing or MD_END not in existing:
        sys.exit(
            f"md_output: markers not found. Add these two lines where the CC "
            f"map should go:\n  {MD_BEGIN}\n  {MD_END}"
        )
    head, rest = existing.split(MD_BEGIN, 1)
    _, tail = rest.split(MD_END, 1)

    rows = [p for p in spec["params"] if p["kind"] in ("float", "enum", "special")]
    by_cat = {c: [] for c in spec["categories"]}
    for p in rows:
        by_cat[p["category"]].append(p)

    out = [MD_BEGIN, "\n\n", f"<!-- generated from {src} -->\n"]
    header = ["CC", "Parameter", "Value range", "CC range", "Description"]
    for cat in spec["categories"]:
        params = sorted(by_cat[cat], key=lambda p: p["cc"])
        if not params:
            continue
        rows = [
            [
                f"CC {p['cc']}",
                p["label"],
                md_value(p) or "—",
                md_range(p),
                p.get("doc", ""),
            ]
            for p in params
        ]
        # Pad to the widest cell per column. The surrounding manual is written
        # with aligned tables and a generated block that is not looks like a
        # mistake in the diff, every time.
        width = [max(md_width(r[i]) for r in [header] + rows) for i in range(5)]
        out.append(f"\n#### {cat}\n\n")
        out.append(md_row(header, width))
        out.append("| " + " | ".join("-" * w for w in width) + " |\n")
        for r in rows:
            out.append(md_row(r, width))
    out.append("\n")
    out.append(MD_END)
    return head + "".join(out) + tail


def outputs(module, spec):
    """Every path this module's params.json generates, in write order."""
    paths = [module / "include" / "param_manifest.generated.h"]
    if spec.get("struct_output"):
        paths.append(module / "include" / spec["struct_output"]["header"])
    if spec.get("globals_output"):
        paths.append(module / "include" / "param_globals.generated.h")
    if spec.get("ts_output"):
        paths.append(module / spec["ts_output"])
    if spec.get("md_output"):
        paths.append(module / spec["md_output"])
    return paths


def main():
    args = sys.argv[1:]
    list_only = "--list-outputs" in args
    args = [a for a in args if a != "--list-outputs"]
    if len(args) != 1:
        sys.exit(__doc__)
    module = pathlib.Path(args[0])
    src = module / "params.json"
    spec = json.loads(src.read_text(encoding="utf-8"))

    if list_only:
        # For `make params-check`: the exact set of paths to diff, so the gate
        # cannot go stale against the generator the way a hand-kept list does.
        for p in outputs(module, spec):
            print(pathlib.Path(os.path.relpath(p.resolve())).as_posix())
        return

    seen = {}
    for p in spec["params"]:
        for key in ("cc", "name"):
            if p[key] in seen.setdefault(key, set()):
                sys.exit(f"duplicate {key}: {p[key]}")
            seen[key].add(p[key])
        if p["category"] not in spec["categories"]:
            sys.exit(f"{p['name']}: unknown category {p['category']!r}")

    dst = module / "include" / "param_manifest.generated.h"
    dst.write_text(gen_cpp(spec, src.as_posix()), encoding="utf-8", newline="\n")

    struct_dst = None
    if spec.get("struct_output"):
        struct_dst = module / "include" / spec["struct_output"]["header"]
        struct_dst.write_text(
            gen_struct(spec, src.as_posix()), encoding="utf-8", newline="\n"
        )

    globals_dst = None
    if spec.get("globals_output"):
        globals_dst = module / "include" / "param_globals.generated.h"
        globals_dst.write_text(
            gen_globals(spec, src.as_posix()), encoding="utf-8", newline="\n"
        )

    ts = spec.get("ts_output")
    if ts:
        tsdst = (module / ts).resolve()
        tsdst.write_text(gen_ts(spec, src.as_posix()), encoding="utf-8", newline="\n")

    md = spec.get("md_output")
    if md:
        mddst = (module / md).resolve()
        before = mddst.read_text(encoding="utf-8")
        after = gen_md(spec, src.as_posix(), before)
        # Only write on a real change: this file is mostly hand-written prose,
        # and rewriting it every run would churn its mtime for nothing.
        if after != before:
            mddst.write_text(after, encoding="utf-8", newline="\n")

    kinds = {}
    for p in spec["params"]:
        kinds[p["kind"]] = kinds.get(p["kind"], 0) + 1
    print(f"{dst}: " + ", ".join(f"{v} {k}" for k, v in sorted(kinds.items())))
    if struct_dst:
        print(
            f"{struct_dst}: {spec['struct_output']['name']}, "
            f"{len(spec['params'])} fields"
        )
    if globals_dst:
        if spec.get("struct_output"):
            print(f"{globals_dst}: {spec['struct_output']['instance']}")
        else:
            print(f"{globals_dst}: {len(spec['params'])} globals")
    if ts:
        print(f"{tsdst}: {len(spec['params'])} params")
    if md:
        print(f"{mddst}: cc-map table {'rewritten' if after != before else 'unchanged'}")


if __name__ == "__main__":
    main()
