#!/usr/bin/env python3
"""Generate parameter tables from a module's params.json.

A parameter used to be declared in up to ten places — the CC table, the serial
command, two halves of the config store, the SysEx dump, the VCV param list and
the web UI map — with three separate "adding a new parameter" checklists that
did not agree with each other. This generator makes params.json the only place
a parameter is described, and emits the rest.

Usage:  python tools/gen_params.py modules/alloyflux
Outputs (committed, so a normal build never needs Python):
    <module>/include/param_manifest.generated.h
"""

import json
import pathlib
import sys

BANNER = "// GENERATED by tools/gen_params.py from {src} — DO NOT EDIT BY HAND.\n"


def fmt_float(v):
    """C++ float literal. Accepts a number or {symbol, value}."""
    if isinstance(v, dict):
        return "(float)" + v["symbol"]
    return f"{v!r}f" if "." in repr(v) or "e" in repr(v) else f"{v}.0f"


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"' if s else "nullptr"


def gen_cpp(spec, src):
    params = [p for p in spec["params"] if p["kind"] == "float"]
    params.sort(key=lambda p: p["cc"])

    out = [BANNER.format(src=src), "#pragma once\n\n"]
    out.append('#include "ParamDescriptor.h"\n')
    for inc in spec.get("cpp_includes", []):
        out.append(f'#include "{inc}"\n')
    out.append("\n")
    out.append("// clang-format off\n")
    out.append("static const ParamDescriptor kParamManifest[] = {\n")
    for p in params:
        target = p["target"]
        # Some targets are declared volatile; the dispatcher writes through a
        # plain float* so those need the qualifier cast away at table build.
        addr = f"const_cast<float *>(&{target})" if p.get("volatile") else f"&{target}"
        out.append(
            "    {{ {cc:3}, {name:<16}, {label:<26}, {cat:<14}, "
            "{mn:>22}, {mx:>26}, {df:>10}, {scale:<16}, {unit:<6}, {addr} }},\n".format(
                cc=p["cc"],
                name=cstr(p["name"]),
                label=cstr(p["label"]),
                cat=cstr(p["category"]),
                mn=fmt_float(p["min"]),
                mx=fmt_float(p["max"]),
                df=fmt_float(p["default"]),
                scale="ParamScale::Log" if p.get("scale") == "log" else "ParamScale::Linear",
                unit=cstr(p.get("unit", "")),
                addr=addr,
            )
        )
    out.append("};\n")
    out.append("// clang-format on\n\n")
    out.append(
        "static const uint8_t kParamManifestCount\n"
        "    = sizeof(kParamManifest) / sizeof(kParamManifest[0]);\n\n"
    )

    enums = [p for p in spec["params"] if p["kind"] == "enum"]
    enums.sort(key=lambda p: p["cc"])

    for h in sorted({p["onChange"] for p in enums if p.get("onChange")}):
        out.append(f"void {h}();\n")
    if enums:
        out.append("\n")

    out.append("// clang-format off\n")
    for p in enums:
        out.append(f"static const ParamOption kOpts_{p['name']}[] = {{\n")
        for o in p["options"]:
            out.append(
                "    {{ {label:<24}, {mn:3}, {mx:3}, {val:3} }},\n".format(
                    label=cstr(o["label"]), mn=o["ccMin"], mx=o["ccMax"], val=o["value"]
                )
            )
        out.append("};\n")
    out.append("\nstatic const EnumParamDescriptor kEnumManifest[] = {\n")
    for p in enums:
        out.append(
            "    {{ {cc:3}, {name:<14}, {label:<26}, {cat:<14}, "
            "(uint8_t *)&{target}, kOpts_{n}, "
            "sizeof(kOpts_{n}) / sizeof(kOpts_{n}[0]), {df:3}, {hook} }},\n".format(
                cc=p["cc"],
                name=cstr(p["name"]),
                label=cstr(p["label"]),
                cat=cstr(p["category"]),
                target=p["target"],
                n=p["name"],
                df=p["default"],
                hook=p.get("onChange") or "nullptr",
            )
        )
    out.append("};\n")
    out.append("// clang-format on\n\n")
    out.append(
        "static const uint8_t kEnumManifestCount\n"
        "    = sizeof(kEnumManifest) / sizeof(kEnumManifest[0]);\n"
    )
    return "".join(out)


def gen_ts(spec, src):
    """Emit the web configurator's parameter map."""
    out = [
        BANNER.format(src=src).replace("//", "//", 1),
        "\n",
        'import type { CCParam } from "./paramMapTypes";\n',
        'export type { CCParam, ParamType, SelectOption } from "./paramMapTypes";\n',
        'export { ccToFloat, floatToCC } from "./paramMapTypes";\n\n',
        "export const PARAM_CATEGORIES = [\n",
    ]
    for c in spec["categories"]:
        out.append(f'  "{c}",\n')
    out.append("] as const;\n\n")
    out.append("export type ParamCategory = (typeof PARAM_CATEGORIES)[number];\n\n")
    out.append("export const PARAM_MAP: CCParam[] = [\n")

    def num(v):
        if isinstance(v, dict):
            return repr(v["value"])
        return repr(v)

    # Authoring order, not CC order: the UI lays parameters out in the sequence
    # they appear in params.json, and that sequence is curated (Mix before Time
    # before Feedback, ADSR after the envelope selectors, and so on). Sorting
    # here would scatter them. The C++ table sorts by CC independently, where
    # order is only a lookup detail.
    for p in spec["params"]:
        out.append("  {\n")
        out.append(f'    cc: {p["cc"]},\n')
        out.append(f'    name: "{p["name"]}",\n')
        out.append(f'    label: "{p["label"]}",\n')
        out.append(f'    category: "{p["category"]}",\n')
        if p["kind"] in ("float", "special"):
            # `display` lets a parameter present in different units from the
            # ones the firmware stores. The CC sent is unchanged either way —
            # only the number next to the slider differs. Used by root, which
            # the module keeps in Hz but which reads far better as semitones.
            d = {**p, **p.get("display", {})}
            out.append(f'    min: {num(d["min"])},\n')
            out.append(f'    max: {num(d["max"])},\n')
            default = d["default"] if "display" not in p else d.get("displayDefault", 0)
            out.append(f'    default: {num(default)},\n')
            if d.get("unit"):
                out.append(f'    unit: "{d["unit"]}",\n')
            if d.get("scale") == "log":
                out.append('    scale: "log",\n')
            if d.get("step") is not None:
                out.append(f'    step: {d["step"]},\n')
            if d.get("ccRange"):
                out.append(
                    f'    ccRange: {{ min: {d["ccRange"]["min"]}, max: {d["ccRange"]["max"]} }},\n'
                )
        else:
            out.append("    min: 0,\n    max: 127,\n")
            out.append(f'    default: {p["options"][0]["ccMin"]},\n')
            out.append('    type: "select",\n')
            out.append("    options: [\n")
            for o in p["options"]:
                out.append(
                    f'      {{ label: "{o["label"]}", ccMin: {o["ccMin"]}, ccMax: {o["ccMax"]} }},\n'
                )
            out.append("    ],\n")
        if p.get("rowBreakBefore"):
            out.append("    rowBreakBefore: true,\n")
        out.append("  },\n")
    out.append("];\n\n")
    out.append(
        "export const PARAMS_BY_CATEGORY = Object.fromEntries(\n"
        "  PARAM_CATEGORIES.map((c) => [c, PARAM_MAP.filter((p) => p.category === c)]),\n"
        ") as Record<ParamCategory, CCParam[]>;\n"
    )
    return "".join(out)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    module = pathlib.Path(sys.argv[1])
    src = module / "params.json"
    spec = json.loads(src.read_text(encoding="utf-8"))

    seen = {}
    for p in spec["params"]:
        for key in ("cc", "name"):
            if p[key] in seen.setdefault(key, set()):
                sys.exit(f"duplicate {key}: {p[key]}")
            seen[key].add(p[key])
        if p["category"] not in spec["categories"]:
            sys.exit(f"{p['name']}: unknown category {p['category']!r}")

    dst = module / "include" / "param_manifest.generated.h"
    dst.write_text(gen_cpp(spec, src.as_posix()), encoding="utf-8", newline="\n")

    ts = spec.get("ts_output")
    if ts:
        tsdst = (module / ts).resolve()
        tsdst.write_text(gen_ts(spec, src.as_posix()), encoding="utf-8", newline="\n")

    kinds = {}
    for p in spec["params"]:
        kinds[p["kind"]] = kinds.get(p["kind"], 0) + 1
    print(f"{dst}: " + ", ".join(f"{v} {k}" for k, v in sorted(kinds.items())))
    if ts:
        print(f"{tsdst}: {len(spec['params'])} params")


if __name__ == "__main__":
    main()
